wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.12
    start_time: 1686044058.416861
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.8.12
      5: 0.14.0
      8:
      - 5
c:
  desc: null
  value: 50
dataset:
  desc: null
  value: movielens
epochs:
  desc: null
  value: 500
l:
  desc: null
  value: 3
name:
  desc: null
  value: NeuCF
path:
  desc: null
  value: pretrained/ncf.h5
save:
  desc: null
  value: true
wandb_entity:
  desc: null
  value: null
