wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.12
    start_time: 1687509671.623945
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.8.12
      5: 0.14.0
      8:
      - 5
batch_size:
  desc: null
  value: 256
c:
  desc: null
  value: 20
dataset:
  desc: null
  value: movielens
epochs:
  desc: null
  value: 1000
l:
  desc: null
  value: 3
latent_factors:
  desc: null
  value: 16
learning_rate:
  desc: null
  value: 0.0005
name:
  desc: null
  value: FedNeuCF
path:
  desc: null
  value: ../../dataset
save:
  desc: null
  value: true
top_k:
  desc: null
  value: 10
type:
  desc: null
  value: ml-100k
validation_steps:
  desc: null
  value: 10
wandb_entity:
  desc: null
  value: null
